# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_firma', '0022_userdocumentsign_xml_pkcs7'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
