# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_firma', '0023_transactionstatus_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominasubida',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominasubida',
            name='tipo',
            field=models.CharField(choices=[(b'ord', b'Ordinaria'), (b'ext', b'Extraordinaria')], default='ord', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominasubida',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
